/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DeadlinesRouteImport } from './routes/deadlines'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SopReviewerRouteImport } from './routes/sop-reviewer'
import { Route as ScholarshipIdRouteImport } from './routes/scholarship.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlinesRoute = DeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SopReviewerRoute = SopReviewerRouteImport.update({
  id: '/sop-reviewer',
  path: '/sop-reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipIdRoute = ScholarshipIdRouteImport.update({
  id: '/scholarship/$id',
  path: '/scholarship/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/copilot': typeof CopilotRoute
  '/deadlines': typeof DeadlinesRoute
  '/documents': typeof DocumentsRoute
  '/funding': typeof FundingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/sop-reviewer': typeof SopReviewerRoute
  '/scholarship/$id': typeof ScholarshipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/copilot': typeof CopilotRoute
  '/deadlines': typeof DeadlinesRoute
  '/documents': typeof DocumentsRoute
  '/funding': typeof FundingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/sop-reviewer': typeof SopReviewerRoute
  '/scholarship/$id': typeof ScholarshipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/copilot': typeof CopilotRoute
  '/deadlines': typeof DeadlinesRoute
  '/documents': typeof DocumentsRoute
  '/funding': typeof FundingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/sop-reviewer': typeof SopReviewerRoute
  '/scholarship/$id': typeof ScholarshipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/copilot'
    | '/deadlines'
    | '/documents'
    | '/funding'
    | '/login'
    | '/profile'
    | '/roadmap'
    | '/signup'
    | '/sop-reviewer'
    | '/scholarship/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/copilot'
    | '/deadlines'
    | '/documents'
    | '/funding'
    | '/login'
    | '/profile'
    | '/roadmap'
    | '/signup'
    | '/sop-reviewer'
    | '/scholarship/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/copilot'
    | '/deadlines'
    | '/documents'
    | '/funding'
    | '/login'
    | '/profile'
    | '/roadmap'
    | '/signup'
    | '/sop-reviewer'
    | '/scholarship/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  CopilotRoute: typeof CopilotRoute
  DeadlinesRoute: typeof DeadlinesRoute
  DocumentsRoute: typeof DocumentsRoute
  FundingRoute: typeof FundingRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RoadmapRoute: typeof RoadmapRoute
  SignupRoute: typeof SignupRoute
  SopReviewerRoute: typeof SopReviewerRoute
  ScholarshipIdRoute: typeof ScholarshipIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlines': {
      id: '/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sop-reviewer': {
      id: '/sop-reviewer'
      path: '/sop-reviewer'
      fullPath: '/sop-reviewer'
      preLoaderRoute: typeof SopReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship/$id': {
      id: '/scholarship/$id'
      path: '/scholarship/$id'
      fullPath: '/scholarship/$id'
      preLoaderRoute: typeof ScholarshipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  CopilotRoute: CopilotRoute,
  DeadlinesRoute: DeadlinesRoute,
  DocumentsRoute: DocumentsRoute,
  FundingRoute: FundingRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RoadmapRoute: RoadmapRoute,
  SignupRoute: SignupRoute,
  SopReviewerRoute: SopReviewerRoute,
  ScholarshipIdRoute: ScholarshipIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
